### ISSUE TITLE
Running time out 

### ISSUE THREAD

**Issue by Mrunal-sudo** [nasa/ISS_Camera_Geolocate#1]
![IMG_20200516_232413](https://user-images.githubusercontent.com/63328901/82126783-762cee00-97cc-11ea-92e8-22676a2675ca.jpg)
Getting issue while installing setup.py 
( running timeout:-cythonize failed)

**Comment by tjlang** [comment]
This looks like an issue installing astropy. You will need to follow up on the astropy GitHub. Unfortunately, I don't know enough about astropy to be helpful to you. But do make sure you have cython installed, in case it's just that.
